
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.syntax;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int VAL = 34;
  public static final int GREATEREQU = 22;
  public static final int LBRACKET = 10;
  public static final int LPAREN = 8;
  public static final int GREATER = 23;
  public static final int INT = 26;
  public static final int LESS = 20;
  public static final int MINUS = 4;
  public static final int RPAREN = 9;
  public static final int NOT = 17;
  public static final int SEMICOLON = 13;
  public static final int AND = 15;
  public static final int FUN = 2;
  public static final int OR = 16;
  public static final int COMMA = 14;
  public static final int DIV = 6;
  public static final int NUM = 37;
  public static final int PLUS = 3;
  public static final int ASSIGN = 7;
  public static final int IF = 31;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 28;
  public static final int RETURN = 35;
  public static final int RBRACKET = 11;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int EQU = 18;
  public static final int LITERAL = 38;
  public static final int NONE = 29;
  public static final int COLON = 12;
  public static final int ELSE = 32;
  public static final int WHILE = 30;
  public static final int NOTEQU = 19;
  public static final int LESSEQU = 21;
  public static final int MULTI = 5;
  public static final int STRING = 27;
  public static final int FALSE = 25;
  public static final int VAR = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUN",
  "PLUS",
  "MINUS",
  "MULTI",
  "DIV",
  "ASSIGN",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "AND",
  "OR",
  "NOT",
  "EQU",
  "NOTEQU",
  "LESS",
  "LESSEQU",
  "GREATEREQU",
  "GREATER",
  "TRUE",
  "FALSE",
  "INT",
  "STRING",
  "BOOLEAN",
  "NONE",
  "WHILE",
  "IF",
  "ELSE",
  "VAR",
  "VAL",
  "RETURN",
  "ID",
  "NUM",
  "LITERAL"
  };
}

